name: Impuls automatic checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Set up Rust, Ninja and mdbtools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo ninja-build mdbtools
          version: 2

      - name: Install dependencies
        run: pip install -r requirements.dev.txt -r requirements.examples.txt

      - name: Cache build artifacts
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            builddir/
            impuls/extern/target/
          key: ${{ runner.os }}-build-${{ hashFiles('impuls/extern/Cargo.toml', 'impuls/extern/Cargo.lock', 'meson.build') }}

      - name: Check meson.build
        run: python check_sources_in_meson_build.py

      - name: Build and install Impuls
        run: |
          pip install --no-build-isolation -Cbuild-dir=builddir --editable .
          ln -s ../../builddir/libextern.so impuls/extern

      - name: Check Python formatting
        run: black --check examples/ impuls/ tests/

      - name: Check Python import ordering
        run: isort --check examples/ impuls/ tests/
        if: ${{ !cancelled() }}

      - name: Lint Python
        run: flake8 examples/ impuls/ tests/
        if: ${{ !cancelled() }}

      - name: Type Check Python
        if: ${{ !cancelled() }}
        uses: jakebailey/pyright-action@v3
        with:
          pylance-version: latest-release
          extra-args: "examples/ impuls/ tests/"

      - name: Run Python tests
        if: ${{ !cancelled() }}
        run: pytest

      - name: Check Rust formatting
        if: ${{ !cancelled() }}
        run: cargo fmt --check
        working-directory: ./impuls/extern/

      - name: Run Rust tests
        if: ${{ !cancelled() }}
        run: cargo test
        working-directory: ./impuls/extern/
